blank_issues_enabled: true
contact_links:
  # - name: Questions
  #   url: Website coming soon.
  #   about: You can join the discussions on Discord.
  - name: New issue
    url: >-
      https://github.com/thomHayner/AIHawk_Birdwatcher/blob/main/.github/CONTRIBUTING.md
    about: "Before opening a new issue, please make sure to read CONTRIBUTING.md"
